### ISSUE TITLE
Setup IntelliJ IDE for GraphHopper core

### ISSUE THREAD

**Issue by karussell** [graphhopper/isochrone-experiments#1]
![image](https://user-images.githubusercontent.com/129644/37524091-1c17eba4-2929-11e8-9930-55edc592300c.png)

![image](https://user-images.githubusercontent.com/129644/37897305-32ea704e-30e6-11e8-8739-12d261e37cd7.png)

![image](https://user-images.githubusercontent.com/129644/37523913-9a87aa84-2928-11e8-8392-b77c61e4eb38.png)

Under Program arguments put:
```
config=config.properties graph.flag_encoders=car,foot datareader.file=berlin-latest.osm.pbf
```

Get PBF:

http://download.geofabrik.de

put into project root.

**Comment by karussell** [comment]
The latest master (0.11) requires slightly different configuration:

![image](https://user-images.githubusercontent.com/129644/39134810-cffc6f9e-4717-11e8-847f-b99b412fdaa3.png)

VM options:
```
-Xmx4g -Xms4g -Dgraphhopper.graph.flag_encoders=car,foot -Dgraphhopper.datareader.file=berlin-latest.osm.pbf -Dgraphhopper.graph.location=graph-cache
```

Program arguments: `server config.yml`

**Comment by boldtrn** [comment]
Should we move this to the core doc, instead of linking? I first thought the [intelliJ link](https://github.com/graphhopper/graphhopper/blob/master/docs/core/quickstart-from-source.md#start-development) would lead to the intelliJ homepage.

I then figured it out myself and wanted to write the documentation for it and stumbled over this link :).

**Comment by karussell** [comment]
Probably, yes.
